name:                ch01
#version:             0.1.0.0
#github:              "githubuser/ch01"
#license:             BSD3
#author:              "Author name here"
#maintainer:          "example@example.com"
#copyright:           "2023 Author name here"
#
#extra-source-files:
#- README.md
#- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
# description:         Please see the README on GitHub at <https://github.com/githubuser/ch01#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- extra
- array
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

# library:
#   source-dirs: src

executables:
  a01:
    main: a01.hs

  b01:
    main: b01.hs

  a02:
    main: a02.hs

  b02:
    main: b02.hs

  a03:
    main: a03.hs

  b03:
    main: b03.hs
  
  a04:
    main: a04.hs

  b04:
    main: b04.hs
  
  a05:
    main: a05.hs

