name:                ch03

dependencies:
- base >= 4.7 && < 5
- bytestring
- extra
- array
- containers
- vector
- mtl
- primitive
- vector-algorithms
- unboxing-vector


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  template:
    main: template.hs
  a11:
    main: a11.hs
  a12:
    main: a12.hs
  a13:
    main: a13.hs
  a14:
    main: a14.hs
  a15:
    main: a15.hs
  b11:
    main: b11.hs
  b12:
    main: b12.hs
  b13:
    main: b13.hs
  b14:
    main: b14.hs
